# Generated by Django 5.0.3 on 2024-08-15 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('info', models.TextField(verbose_name='Izoh')),
                ('slug', models.SlugField(unique=True, verbose_name='manzil')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
            },
        ),
    ]
