# Generated by Django 5.0.3 on 2024-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozodapp', '0002_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.IntegerField(default=0, verbose_name="ko'rganlar soni"),
        ),
    ]
